[project]
name = "mcp-fegis-server"
authors = [
    { name = "Perry Golden", email = "goldenp@ptology.com" },
]
version = "1.0.0"
description = "A schema-driven memory engine that gives LLMs structured tools and persistent memory."
readme = "README.md"
license = "PolyForm-Noncommercial-1.0.0"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
    "pyyaml>=6.0.2",
    "qdrant-client[fastembed]>=1.13.3",
    "pydantic>=2.10.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
fegis = "mcp_fegis_server.main:main"

[project.urls]
repository = "https://github.com/pfunk/FEGIS"
